# Creating environments to simulate the SVC-A2C (Actor Critic Algorithm to Improve Smart Vacuum Cleanner)

### Each environment will be a Matrix with m lines and n columns
m = 100

n = 100

Each cell represent a space of $20 cm^2$

The values that could be in cell are:

* 0 --> free and clean space;
* 1 --> free and low dirty
* 2 --> free and high dirty
* 3 --> Blocked space

The environment have $400m^2$ ($20mx20m$).

In [1]:
import numpy as np
import gym
import gym_svc_env

In [18]:
env = gym.make('svc-v0')
env.reset()

array([[[1, 1, 3, 3],
        [1, 1, 1, 3],
        [3, 0, 1, 3],
        [1, 3, 0, 3],
        [1, 1, 3, 3]],

       [[1, 1, 3, 3],
        [1, 1, 1, 3],
        [1, 1, 1, 3],
        [1, 1, 1, 3],
        [1, 1, 3, 3]],

       [[1, 1, 3, 3],
        [0, 3, 1, 3],
        [3, 1, 1, 3],
        [1, 1, 1, 3],
        [1, 1, 3, 3]],

       [[3, 1, 1, 3],
        [1, 1, 1, 3],
        [1, 0, 1, 3],
        [3, 3, 1, 3],
        [1, 1, 3, 3]],

       [[1, 1, 1, 3],
        [1, 1, 1, 3],
        [1, 1, 1, 3],
        [3, 1, 1, 3],
        [1, 3, 3, 3]]])

In [25]:
print(env.step(1))
env.render()

(array([[[0, 1, 1, 3],
        [0, 0, 1, 3],
        [1, 1, 1, 3],
        [0, 1, 3, 3],
        [3, 1, 3, 3]],

       [[1, 1, 3, 3],
        [3, 1, 1, 3],
        [1, 3, 1, 3],
        [1, 0, 0, 3],
        [1, 1, 3, 3]],

       [[3, 3, 0, 3],
        [1, 1, 3, 3],
        [1, 2, 1, 3],
        [1, 1, 3, 3],
        [1, 1, 3, 3]],

       [[1, 1, 0, 3],
        [1, 1, 1, 3],
        [1, 1, 3, 3],
        [1, 1, 0, 3],
        [1, 1, 3, 3]],

       [[0, 1, 0, 3],
        [1, 0, 1, 3],
        [1, 0, 0, 3],
        [3, 0, 2, 3],
        [1, 2, 3, 3]]]), -0.2, False, {})
[[3. 3. 3. ... 3. 3. 3.]
 [3. 1. 1. ... 1. 1. 3.]
 [3. 1. 3. ... 3. 0. 3.]
 ...
 [3. 1. 1. ... 1. 1. 3.]
 [3. 1. 1. ... 0. 1. 3.]
 [3. 3. 3. ... 3. 3. 3.]]
[[0 0 1 0 3]
 [1 3 1 1 1]
 [3 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 3 1]]

[[1 0 1 1 1]
 [1 1 3 0 1]
 [3 1 2 1 1]
 [1 1 1 1 1]
 [1 0 0 0 2]]

[[1 1 1 3 3]
 [3 1 1 0 3]
 [0 3 1 3 3]
 [0 1 3 0 3]
 [0 1 0 2 3]]

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]

In [21]:
env.reset()
env.step(env.action_space.sample)

AssertionError: <bound method Discrete.sample of Discrete(5)> (<class 'method'>) invalid

In [4]:
env = gym.make('CartPole-v1')

In [63]:
env.close()